name: Deploy to Surge

on:
  push:
    branches:
      - gh-pages  # 替换为你需要的分支名称
  workflow_dispatch: # 添加手动触发支持

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Surge
        run: |
          npm install -g surge
          surge ./ https://acofork-blog.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
