name: Deploy to Surge

on:
  push:
    branches:
      - gh-pages  # 替换为你需要的分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Surge
        run: |
          npm install -g surge
          surge ./ https://surge-blog.acofork.us.kg --token ${{ secrets.SURGE_TOKEN }}
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
